### ISSUE TITLE
4WD and Mecanum drive wiring

### ISSUE THREAD

**Issue by zhuwei** [linorobot/linorobot#38]
Hi, guys.
Do you have to use 4 L298N for 4WD and Mecanum drive wiring?

**Comment by STMBenke** [comment]
No,I think you can use two l298's to control it, because it has two output controls.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kerr"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月19日(星期二) 下午3:00
收件人:&nbsp;"linorobot/linorobot"<linorobot@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[linorobot/linorobot] 4WD and Mecanum drive wiring (#38)




Hi, guys.
 Do you have to use 4 L298N for 4WD and Mecanum drive wiring?

**Comment by zhuwei** [comment]
Thank you for your answer.
